@startuml Route-map
start
:Подготовительный этап;
:Настройка коммутаторов для поддержки протокола LLDP;
:Настройка портов коммутаторов на автоматическое определение VLAN;
:Настройка SNMP на коммутаторах и на сервере Flask;
:Создание Docker-контейнеров для серверной и клиентской частей приложения;
:Разработка серверной части;
:Написание приложения на сервере Flask для принятия триггеров от коммутаторов;
:Написание приложения на сервере Flask для получения информации о подключенных устройствах при помощи протокола LLDP;
:Написание приложения на сервере Flask для автоматической настройки ОС, добавления к домену, настройки имени ПК и пользователя на основании информации, полученной при помощи протокола LLDP;
:Написание приложения на сервере Flask для выбора необходимого пользователю ПО;
:Разработка клиентской части;
:Написание приложения для отправки триггеров на сервер Flask при поднятии порта;
:Написание приложения для получения информации о подключенном устройстве при помощи протокола LLDP и отправки ее на сервер Flask;
:Тестирование и отладка;
:Настройка Docker Compose для запуска контейнеров серверной и клиентской частей приложения;
:Опубликование Docker-контейнеров в Docker Hub или другом репозитории контейнеров;
:Настройка автоматического развертывания приложения при помощи средств CI/CD (например, Jenkins, CircleCI);
:Поддержка и обновление;
:Поддержание приложения в актуальном состоянии, выпуск обновлений и исправление ошибок;
:Организация процесса мониторинга и логирования для быстрого выявления и устранения проблем;
:Проведение регулярного тестирования и анализа производительности приложения, чтобы обеспечить его высокую работоспособность и эффективность;
stop
@enduml
