graph TD;
  A[Клиент]
  B[Телефон]
  C[Электронная почта]
  D[Форма на сайте]
  E[Чат на сайте]
  F[Мессенджеры]
  G[Отдел сбыта]
  A-- Связывается по телефону -->B
  A-- Связывается по электронной почте -->C
  A-- Заполняет форму на сайте -->D
  A-- Начинает онлайн-чат на сайте -->E
  A-- Связывается через мессенджеры -->F
  B-- Передает запрос на обработку -->G
  C-- Передает запрос на обработку -->G
  D-- Передает запрос на обработку -->G
  E-- Передает запрос на обработку -->G
  F-- Передает запрос на обработку -->G
